# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f03d3a4f670539284630ed9ef28ed564b89737c1e233c95d7b98c87bd17fd4981325aecb9e64150d107fa72d888f728d6abdf036d97881cccf887dd7603c1cc

test:
  secret_key_base: 7ab53021e256dadaa292145554c44b665b036e677c142fda3e895af8e54a90372988d9c4649278d650a3358161cb668740af9af175a87d2e340f77d6b866fa55

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
